### ISSUE TITLE
cant find the file specified

### ISSUE THREAD

**Issue by moosje2003** [SuperZombi/GICutscenesUI#14]
when ever i launch and try to covert a file it gets stuck here 
![image](https://user-images.githubusercontent.com/61630365/196676026-74280e1a-3bc8-493f-96e5-1ad4d295e773.png)
and i get this error code
Traceback (most recent call last):
  File "eel\__init__.py", line 281, in _process_message
  File "main.py", line 341, in start_work
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by SuperZombi** [comment]
You need to provide the path to the TaoHantor's script
<https://github.com/ToaHartor/GI-cutscenes>, not to the GUI.exe
Download release from his repository and then open my UI:
Settings > GI-cutscenes.exe > Change

ср, 19 окт. 2022 г. в 14:14, moosje2003 ***@***.***>:
