### ISSUE TITLE
Is that able to be used through Edge?

### ISSUE THREAD

**Issue by LainHE** [SuperZombi/GICutscenesUI#9]
Hi,

I am using Edge and it is based on Chromium. However the GICutscenesUI.exe still unable to run, which shows:
```
Traceback (most recent call last):
  File "main.py", line 309, in <module>
  File "eel\__init__.py", line 158, in start
  File "eel\__init__.py", line 186, in show
  File "eel\browsers.py", line 65, in open
OSError: Can't find Google Chrome/Chromium installation
[8392] Failed to execute script 'main' due to unhandled exception!
```
I really don't want to install a new browser..
Is that able to support Edge? Or by using Chromedrive or something? Sorry, I don't know much about front end..

**Comment by SuperZombi** [comment]
Please download the latest version from the releases and test the functionality.

**Comment by LainHE** [comment]
Thx, It worked.
